# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        carree: # nom du filtre
            quality: 75 #Qualité de l'image
            filters: 
                thumbnail: 
                    size: [200,200] #et 11 aussi decouper l'image
                    mode: outbound
                    
